/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./components/components/ButtonComponent.vue')['default']
    CanvasArea: typeof import('./components/editor/CanvasArea.vue')['default']
    CanvasSettings: typeof import('./components/editor/CanvasSettings.vue')['default']
    ChartComponent: typeof import('./components/components/ChartComponent.vue')['default']
    ComponentPanel: typeof import('./components/editor/ComponentPanel.vue')['default']
    ContainerComponent: typeof import('./components/components/ContainerComponent.vue')['default']
    ContextMenu: typeof import('./components/editor/ContextMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ImageComponent: typeof import('./components/components/ImageComponent.vue')['default']
    InputComponent: typeof import('./components/components/InputComponent.vue')['default']
    LayerPanel: typeof import('./components/editor/LayerPanel.vue')['default']
    PropertyPanel: typeof import('./components/editor/PropertyPanel.vue')['default']
    RenderComponent: typeof import('./components/editor/RenderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextComponent: typeof import('./components/components/TextComponent.vue')['default']
    Toolbar: typeof import('./components/editor/Toolbar.vue')['default']
  }
}
